title: Sean's Awesome Metal Thing
author: Sean
email: sprus1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
instagram_username: de.memes.dom.sathanas
github_username:  DarthBaragon666

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
